# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddcbf05ae0d0d6f9c32722257d7c9976032eaff00f38a6b287fe5a812b2a92f7080bcca0e752cd22b34f8a0983872deb9c8b84f6cb363f40276a5bab90477691

test:
  secret_key_base: 6e5ffe7ab98e948facae5bd07edd7d7d1eb52d77d73faea2023daceb12425dfee0ac78fd5b90bebef59d5ec01fa421989804edbf69760386d4ddcb4ca988282e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
